version: '3.7'

networks:
  local_beach:
    external: true

services:
  webserver:
    image: ${BEACH_WEBSERVER_IMAGE:-flownative/nginx}:${BEACH_WEBSERVER_IMAGE_VERSION:-3}
    container_name: ${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_webserver
    networks:
      - local_beach
    ports:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - ./:/application
    environment:
      - VIRTUAL_HOST=${BEACH_VIRTUAL_HOSTS:?Please specify Beach virtual hosts as BEACH_VIRTUAL_HOSTS}
      - VIRTUAL_PORT=8080
      - BEACH_PHP_FPM_HOST=${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_php
      - BEACH_FLOW_BASE_CONTEXT=${BEACH_FLOW_BASE_CONTEXT:-Development}
      - BEACH_FLOW_SUB_CONTEXT=${BEACH_FLOW_SUB_CONTEXT:-Instance}
      - BEACH_PHP_MEMORY_LIMIT=${BEACH_PHP_MEMORY_LIMIT:-750M}
      - BEACH_PERSISTENT_RESOURCES_FALLBACK_BASE_URI=${BEACH_PERSISTENT_RESOURCES_FALLBACK_BASE_URI:-}
      - FLOW_HTTP_TRUSTED_PROXIES=*
      - NGINX_CACHE_ENABLE=false

  php:
    image: ${BEACH_PHP_IMAGE:-flownative/beach-php}:${BEACH_PHP_IMAGE_VERSION:-8.3}
    container_name: ${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_php

    networks:
      - local_beach
    depends_on:
      - webserver
      - redis
    security_opt:
      - no-new-privileges
    volumes:
      - ./:/application
    environment:
      - BEACH_WAIT_FOR_SYNC=false
      - BEACH_INSTANCE_NAME=${BEACH_PROJECT_NAME}
      - BEACH_FLOW_BASE_CONTEXT=${BEACH_FLOW_BASE_CONTEXT:-Development}
      - BEACH_FLOW_SUB_CONTEXT=${BEACH_FLOW_SUB_CONTEXT:-Instance}
      - BEACH_DATABASE_HOST=${BEACH_DATABASE_HOST:-local_beach_database.local_beach}
      - BEACH_DATABASE_PORT=${BEACH_DATABASE_PORT:-3306}
      - BEACH_DATABASE_NAME=${BEACH_PROJECT_NAME}
      - BEACH_DATABASE_USERNAME=${BEACH_DATABASE_USERNAME:-root}
      - BEACH_DATABASE_PASSWORD=${BEACH_DATABASE_PASSWORD:-password}
      - BEACH_REDIS_HOST=${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_redis.local_beach
      - BEACH_REDIS_PORT=${BEACH_REDIS_PORT:-6379}
      - BEACH_REDIS_PASSWORD=${BEACH_REDIS_PASSWORD:-password}
      - BEACH_PHP_MEMORY_LIMIT=${BEACH_PHP_MEMORY_LIMIT:-750M}
      - BEACH_PHP_TIMEZONE=${BEACH_PHP_TIMEZONE:-UTC}
      - BEACH_APPLICATION_USER_SERVICE_ENABLE=${BEACH_APPLICATION_USER_SERVICE_ENABLE:-false}
      - BEACH_APPLICATION_STARTUP_SCRIPTS_ENABLE=${BEACH_APPLICATION_STARTUP_SCRIPTS_ENABLE:-false}
      - BEACH_APPLICATION_CUSTOM_STARTUP_SCRIPTS_ENABLE=${BEACH_APPLICATION_CUSTOM_STARTUP_SCRIPTS_ENABLE:-false}
      - ELASTICSEARCH_HOSTNAME=${ELASTICSEARCH_HOSTNAME:-neosio_elasticsearch.local_beach}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - CROWD_API_USERNAME=${CROWD_API_USERNAME:-}
      - CROWD_API_PASSWORD=${CROWD_API_PASSWORD:-}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN:-}

  redis:
    image: ${BEACH_REDIS_IMAGE:-flownative/redis}:${BEACH_REDIS_IMAGE_VERSION:-latest}
    container_name: ${BEACH_PROJECT_NAME:?Please specify a Beach project name as BEACH_PROJECT_NAME}_redis
    networks:
      - local_beach
    environment:
      - REDIS_MAX_MEMORY=${BEACH_REDIS_MAX_MEMORY:-50000000}
      - REDIS_PASSWORD=${BEACH_REDIS_PASSWORD:-password}
    healthcheck:
      test: "/healthcheck.sh --liveness"
      interval: 1s
      timeout: 5s
      retries: 120
