
Neos:
  NeosIo:
    fundingApi:
      username: ''
      password: ''
      apiUrl: 'https://neosfunding.sandstorm.de'
      timeout: 30
      actions:
        getBadges: /funding-api-sold-badges
      parameters: {  }
    crowdApi:
      username: neos.io-teams
      password: ''
      apiUrl: 'https://crowd.neos.io/rest/usermanagement/1'
      timeout: 30
      actions:
        search: /search.json
        getGroup: /group.json
        getGroupMembers: /group/user/direct.json
        setGroupAttributes: /group/attribute.json
        getUser: /user.json
        setUserAttributes: /user/attribute.json
      parameters:
        active: true
      additionalAttributes:
        group:
          - neos_group_type
          - neos_title
          - neos_summary
        user:
          - neos_website
          - neos_skype
          - neos_twitter
          - neos_email
          - neos_origin
          - neos_bio
          - neos_contribution
  Form:
    presets:
      'fusion':
        title: 'Fusion based Form Elements'
        parentPreset: 'default'
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              templatePathPattern: ~
              partialPathPattern: ~
              layoutPathPattern: ~
          'Neos.Form:Form':
            rendererClassName: 'Neos\Form\FusionRenderer\FusionFormRenderer'
            renderingOptions:
              submitButtonClassAttribute: 'btn btn--solidPrimary'

  Flow:
    http:
      applicationToken: 'MajorVersion'
    mvc:
      routes:
        'Neos.NeosIo':
          position: 'before Neos.Neos'

  Neos:
    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
      inspector:
        editors:
          Neos.Neos/Inspector/Editors/LinkEditor:
            editorOptions:
              nodeTypes:
                - 'Neos.NodeTypes:Page'
                - 'Neos.MarketPlace:RepositoryStorage'
                - 'Neos.NeosIo:Reference'
    nodeTypes:
      groups:
        special:
          position: 'after general'
          label: Special

  ContentRepository:
    contentDimensions:
      'language':
        default: 'en'
        defaultPreset: 'en'
        label: 'Language'
        icon: 'icon-language'
        presets:
          'en':
            label: 'English'
            values: ['en']
            uriSegment: ''
          'de':
            label: 'German'
            values: ['de', 'en']
            uriSegment: 'de'
  Fusion:
    defaultContext:
      Data: Neos\NeosIo\Eel\Helper\DataHelper
      NeosIo_Event: Neos\NeosIo\Eel\Helper\EventHelper

PunktDe:
  CodeView:
    loadCSS: false
    loadJS: true
