Neos:
  Fusion:
    defaultContext:
      Data: Neos\NeosIo\Eel\Helper\DataHelper
      Number: Neos\NeosIo\Eel\Helper\NumberHelper
      NeosIo_Event: Neos\NeosIo\Eel\Helper\EventHelper
      Gravatar: Neos\NeosIo\Eel\Helper\GravatarHelper
      NeosIo.Node: Neos\NeosIo\Eel\Helper\NodeHelper
