Neos:
  Media:
    autoCreateThumbnailPresets: false
    image:
      defaultOptions:
        quality: 95
        webp_quality: 95
        jpeg_quality: 95
        png_compression_level: 1

  Neos:
    modules:
      management:
        submodules:
          media:
            enabled: false
          mediaui:
            position: start
