
Neos:
  Neos:
    nodeTypes:
      groups:
        neoscon:
          label: neoscon.io
          position: 45

  Fusion:
    defaultContext:
      'Neos.NeosConIo.Date': 'Neos\NeosConIo\Eel\DateHelper'
