Neos:
  MarketPlace:
    # when packages are indexed the following packages and their versions are checked for compatibility
    # to allow filtering in the package search by supported version
    compatibilityCheck:
      neos/neos:
        - '8.1'
        - '8.0'
        - '7.3'
        - '7.2'
        - '7.1'
        - '7.0'
        - '5.3'
        - '4.3'
      neos/flow:
        - '8.1'
        - '8.0'
        - '7.3'
        - '7.2'
        - '7.1'
        - '7.0'
        - '6.3'
        - '5.3'
    # composer types to include, optional with a mapping to a current type
    typeMapping:
      neos-plugin: neos-plugin
      typo3-flow-build: neos-build
      typo3-flow-boilerplate: neos-boilerplate
      neos-site: neos-site
      neos-package: neos-package
      neos-framework: neos-framework
      neos-build: neos-build
      neos-boilerplate: neos-boilerplate
      neos-carbon: neos-carbon
    vendorMapping:
      neos: true
      flowpack: true
    packageBlackList:
      neos/app: true
      neos/data: true
      neos/html: true
      neos/image: true
      neos/lib: true
      neos/limp: true
      neos/plim: true
      neos/start: true
      neos/start-blog: true
      neos/start-skel: true
      neos/tiga: true
    repository:
      identifier: 9127231f-d1b8-440f-8ef7-b05f760178fb
    github:
      cacheDirectory: '%FLOW_PATH_DATA%Github/Cache'
      # Please create a personal access token to access this endpoint: http://github.com/settings/tokens
      token: set-token

  Flow:
    mvc:
      routes:
        Neos.MarketPlace:
          position: 'before Neos.Neos'

  Neos:
    nodeTypes:
      groups:
        marketplace:
          position: 'after general'
          label: 'Neos.MarketPlace:Main:nodeTypes.groups.marketplace'
    userInterface:
      translation:
        autoInclude:
          Neos.MarketPlace:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Neos.MarketPlace: true

  ContentRepository:
    Search:
      realtimeIndexing:
        enabled: false
      defaultContext:
        MarketIndexing: Neos\MarketPlace\Eel\IndexingHelper

  Fusion:
    defaultContext:
      MarketPlaceSearch: Neos\MarketPlace\Eel\ElasticSearchQueryBuilder

Ttree:
  OutOfBandRendering:
    presets:
      'marketplace:version':
        path: 'root<Neos.Fusion:Case>/neosMarketPlaceDocument<Neos.Fusion:Matcher>/element<Neos.MarketPlace:Package>/body<Neos.Fusion:Template>/content/main<Neos.Fusion:Array>/package<Neos.MarketPlace:Package>/versions<Neos.MarketPlace:VersionPreview>'
